app/controllers/proyectController.py
from flask import Flask, request, redirect, url_for, flash,Response, stream_with_context
from flask import session as sesion
from flask import Blueprint, render_template
import face_recognition
import cv2
import numpy as np
from app import db
from app import app


import time

import os
from werkzeug.utils import secure_filename
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.orm import sessionmaker
from sqlalchemy import create_engine, desc
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.sql import func

from app.Model.Model import Examen
from app.Model.Model import Usuario


engine = create_engine('mysql+pymysql://root:@localhost/reconocimiento')
Session = sessionmaker(bind=engine)
session = Session()



camera = cv2.VideoCapture(0)




#SEGUIR CON LA LIBRERIA LOGIN

#DEFINICIÓN DE TODAS LAS FUNCIONES
face_recognition_Route = Blueprint('face_recognition',__name__)

class Loging():
    #DEFINICION DE LA RUTA RAIZ DE LOGIN
    @face_recognition_Route.route('/',methods=['GET','POST'])
    def login():
        if request.method == 'POST':
            email = request.form['email']
            password = request.form['password']
            user = session.query(Usuario.id).filter_by(correo=email,contraseña=password).scalar()
            print('entro2')
            if user:
                sesion['user'] = user
                return redirect('/home')
            if not user:
                flash('Contraseña incorrecta')
                return render_template('login.html')
        return render_template('login.html')

    #DEFINICION DE LA RUTA DE HOME, PANTALLA PRINCIPAL
    @face_recognition_Route.route('/home')
    def index():
        if 'user' in sesion:
            print(sesion['user'])
            return render_template('index.html')
        return redirect('/')
    #DEFINICION DEL TEMPLATE DE INDICACIONES
    @face_recognition_Route.route('/indicaciones')
    def indicaciones():
        if 'user' in sesion:
            #LE INDICAMOS AL PROGRAMA QUE EN LA BD EL ATRIBUTO RECONOCIDO ES UN FALSE
            id_de_sesion= sesion['user']
            user = session.query(Examen).filter_by(idUsuario=id_de_sesion).first()
            print(user)
            user.Reconocido = False
            session.commit()
            return render_template('indicaciones.html')
        return redirect('/')
    
    #DEFINICION DE LA RUTA DE DONDE SE SUBE LA FOTO DEL USUARIO 
    @face_recognition_Route.route('/inicio')
    def inicio():
        if 'user' in sesion:
            return render_template('inicio.html')
        return redirect('/')
    
    @face_recognition_Route.route('/activar')
    def activar():
        if 'user' in sesion:
            print(sesion['user'])
            return render_template('activar.html')
        return redirect('/')

    #VALIDACION DEL ROSTRO DEL USUARIO
    @face_recognition_Route.route('/validacion')
    def validarFace():
        time.sleep(5)
        user = session.query(Examen).filter_by(idUsuario=sesion['user']).first()
        if user.Reconocido:
           return redirect('https://www.educa-t.unach.mx/login/index.php')
        else:
            flash('Rostro no reconocido vuelve a intentarlo...')
            return redirect('/activar')


    #GUARDAR LA IMAGEN DEL USUARIO EN FORMATO ESPECIFICADO
    @face_recognition_Route.route('/aceptar', methods=['POST'])
    def aceptar():
        ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}
        _matricula=request.form['txtmatricula']
        _nombre=request.form['txtnombre']
        _archivo=request.files['customFile']
        #print(_archivo)
        if _matricula =='' or _nombre =='' or _archivo.filename=='':
            flash('Recuerda Llenar Todos los Campos')
            return redirect('registrar')
        filename = secure_filename(str(_matricula) +".jpg")
        print(filename)
        # Guardamos el archivo en el directorio "Archivos PDF"
        _archivo.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
        
        # Retornamos una respuesta satisfactoria
        return redirect('/home')
    #REDIRECCIONAMIENTO AL TEMPLATE DE GUARDAR FOTO
    @face_recognition_Route.route('/registrar')
    def registrar():
        if 'user' in sesion:
            return render_template('registrar.html')
        return redirect('/')


    #aQUI OCURRE LA MAGIA DEL RECONOCIMIENTO FACIAL
    @face_recognition_Route.route('/video_feed')
    def video_feed():
        id_de_sesion= sesion['user']
        def gen_frames():  
            
            flag = 0
            matricula = session.query(Usuario.Matricula).filter_by(id=id_de_sesion).first()
            print(matricula)
            #LE PASAMOS EL VALOR DE LA SESION DEL USUARIO PARA BUSCAR SU ROSTRO
            obama_image = face_recognition.load_image_file("./app/static/alumnos/"+matricula[0]+".jpg")
            print(obama_image)
            obama_face_encoding = face_recognition.face_encodings(obama_image)[0]


            # Create arrays of known face encodings and their names
            known_face_encodings = [
                obama_face_encoding
            ]
            known_face_names = [
                #AQUI PONEMOS EL NOMBRE DE LA MATRICULA EN LA PANTALLA DE RECONOCIMIENTO FACIAL
                matricula[0],
            ]

            # Initialize some variables
            face_locations = []
            face_encodings = []
            face_names = []
            process_this_frame = True
            var = True
            flag = 0
            while var :
                success, frame = camera.read()  # read the camera frame

                small_frame = cv2.resize(frame, (0, 0), fx=0.25, fy=0.25)

                rgb_small_frame = small_frame[:, :, ::-1]

                if process_this_frame:
                    # Find all the faces and face encodings in the current frame of video
                    face_locations = face_recognition.face_locations(rgb_small_frame)
                    face_encodings = face_recognition.face_encodings(rgb_small_frame, face_locations)

                    face_names = []
                    #FOR QUE BUSCA EL ROSTRO ENTRE LAS IMAGENES DADAS
                    for face_encoding in face_encodings:
                        # See if the face is a match for the known face(s)
                        matches = face_recognition.compare_faces(known_face_encodings, face_encoding)
                        name = "Unknown"

                        # # If a match was found in known_face_encodings, just use the first one.
                        # if True in matches:
                        #     first_match_index = matches.index(True)
                        #     name = known_face_names[first_match_index]

                        # Or instead, use the known face with the smallest distance to the new face
                        face_distances = face_recognition.face_distance(known_face_encodings, face_encoding)
                        best_match_index = np.argmin(face_distances)
                        if matches[best_match_index]:
                            name = known_face_names[best_match_index]

                        face_names.append(name)
                        
                        for item in face_names:
                            #CONVERTIMOS EN TRUE EL ATRIBUTO RECONOCIMIENTO, Y SE VALIDA EL USUARIO
                            if item == matricula[0] and flag == 0:
                                user = session.query(Examen).filter_by(idUsuario=id_de_sesion).first()
                                user.Reconocido = True
                                session.commit()
                                print('entro')
                                flag = 1
                                
                process_this_frame = not process_this_frame   
                for (top, right, bottom, left), name in zip(face_locations, face_names):
                    # Scale back up face locations since the frame we detected in was scaled to 1/4 size
                    top *= 4
                    right *= 4
                    bottom *= 4
                    left *= 4
                    # SE DEFINE EL TAMAÑO DEL FRAME DE LA CAMARA
                    # Draw a box around the face
                    cv2.rectangle(frame, (left, top), (right, bottom), (0, 0, 255), 2)

                    # Draw a label with a name below the face
                    cv2.rectangle(frame, (left, bottom - 35), (right, bottom), (0, 0, 255), cv2.FILLED)
                    font = cv2.FONT_HERSHEY_DUPLEX
                    cv2.putText(frame, name, (left + 6, bottom - 6), font, 1.0, (255, 255, 255), 1)
                    
                if not success:

                    break
                    
                else:
                    ret, buffer = cv2.imencode('.jpg', frame)
                    frame = buffer.tobytes()
                    yield (b'--frame\r\n'
                        b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')  # concat frame one by one and show result

        

        return  Response(gen_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')
        
        #SE RESUELVE AL INSERTAR TRUE EN UNA BD Y LUEGO PREGUNTAR SI YA ESTA TRUE PARA QUE PROSIGA EL EXAMEN

app/templates/activar.html
{% include 'header.html' %}

<link rel="stylesheet" href="{{ url_for('static',filename='/css/botones.css') }}">


<h2 class="text-center">Verifique su identidad</h2>
<br><br><br>

{% for message in get_flashed_messages() %}
<div class="alert alert-warning">{{ message }}</div>
{% endfor %}
  

<div class="container">
  <center> 
    <div class="card shadow-lg p-3 mb-3 bg-white rounded">
      <div class="card-body">
        <img id="bg" src="{{ url_for('face_recognition.video_feed') }}"> 
      </div>
    </div>
    
  
  </center>
</div>

<br><br><br><br>

<br><br>
<div class="row align-items-end">
    <div class="col"></div>
    <div class="col"></div>

    
    
    <a href="{{ url_for('face_recognition.validarFace') }}">
    <button type="button" class="btn text-white" style="background-color: #18386B"  data-toggle="modal" data-target="#exampleModalCenter">
      Validar rostro
    </button> 
    </a>
      <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalCenterTitle">Validando rostro</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <center>
              <div class="spinner-border text-primary" role="status">
                <p class="sr-only">Cargando...</p>
              </div>
            </center>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
          </div>
        </div>
      </div>
    </div>
</div>
  


{% include 'footer.html' %}

app/templates/footer.html
</div> 


    </body>
    <link rel="stylesheet" href="{{ url_for('static',filename='/css/footer.css') }}">
    <br><br>
<footer class="footer">
    <!-- Grid container -->
    <div class="container p-4">
      <!--Grid row-->
      <div class="row">
        <!--Grid column-->
        <div class="col-lg-4">
            <a class="navbar-brand" href="https://www.unach.mx/avisos-de-privacidad#facultad-de-lenguas-campus-tuxtla">Aviso de Privacidad</a>
        </div>
        <!--Grid column-->
  
        <!--Grid column-->
        <div class="col-lg-4">
            <a class="navbar-brand" href="https://transparencia.unach.mx/">Transparencia</a>
        </div>
        <!--Grid column-->
         <!--Grid column-->
        <div class="col-lg-4">
            <a class="navbar-brand" href="https://www.unach.mx/">Universidad Autónoma de Chiapas</a>
        </div>
        <!--Grid column-->
         <!--Grid column-->
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </div>



    <footer class="text-center text-white" style="background-color: #D2A82C">
        <!-- Grid container -->
        <div class="container p-4 pb-0">
          <!-- Section: Social media -->
          <section class="mb-4">
            <!-- Facebook -->
            <a
              class="btn btn-primary btn-floating m-1"
              style="background-color: #D2A82C;"
              href="https://www.facebook.com/comunicaunach/"
              role="button">
              <img src="{{ url_for('static',filename='/imagenes/facebook1.png') }}" alt="" width="30" height="30">
              <i class="fab fa-facebook-f"></i
            ></a>
      
            <!-- Twitter -->
            <a
              class="btn btn-primary btn-floating m-1"
              style="background-color: #D2A82C;"
              href="https://twitter.com/comunica_unach"
              role="button">
              <img src="{{ url_for('static',filename='/imagenes/twitter1.png') }}" alt="" width="30" height="30">
              <i class="fab fa-twitter"></i
            ></a>
      
            <!-- Google -->
            <a
              class="btn btn-primary btn-floating m-1"
              style="background-color: #D2A82C;"
              href="https://www.youtube.com/channel/UCBZeuAGfjUpPVmwBlU9S6GQ"
              role="button">
              <img src="{{ url_for('static',filename='/imagenes/youtube.png') }}" alt="" width="30" height="30">
              <i class="fab fa-google"></i
            ></a>
        </div>
        <!-- Grid container -->
    </footer>

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: #18386B;">
      © 2021 Copyright:
      <a class="text-white" href="#">IonHack</a>
    </div>
    <!-- Copyright -->
  </footer>
</html>

app/templates/header.html
<!doctype html>
<html lang="en">
  <head>
    
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{ url_for('static',filename='/css/styleHeader.css') }}">
    <!-- Bootstrap CSS -->
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
  </head>
  <body .bg-white>
    
    <table class="table">
      <thead>
        <tr>
          <nav class="navbar navbar-expand-lg">
            
            </div>
            
            
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" ><span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <img src="{{ url_for('static',filename='/imagenes/unach.png') }}" alt="" class="img-thumbnail"  width="100" height="140">
                </li>
                <li class="nav-item">
                  <a class="nav-link" ></a>
                </li>
                <li class="nav-item">
                  <img src="{{ url_for('static',filename='/imagenes/lenguas1.png') }}" alt="" class="img-thumbnail" width="80" height="100">
                </li>
                <li class="nav-item">
                  <a class="nav-link" ></a>
                </li>
                <li class="nav-item">
                  <a href="{{ url_for('face_recognition.index') }}" style="color: white;" class="nav-link">FACULTAD DE LENGUAS <br>TUXTLA GUTIÉRREZ <br>C-I</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" ></a>
                </li>
               
              </ul>
            
          </nav>
        </tr>
      </thead>
      <tbody>
        <tr>
          <nav class="navbar navbar-light shadow-lg" style="background-color: #D2A82C">
            <div class="container-fluid">
              <span class="navbar-text">
                Reconocimiento facial 
              </span>
            </div>
          </nav>
       
        </tr>
      </tbody>
    </table>



 
    


    
      
     <div class=container>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

app/templates/index.html
{% include 'header.html' %}

<link rel="stylesheet" href="{{ url_for('static',filename='/css/stylebody.css') }}">
<center>
  <h1>Bienvenid@ a FREE.IA</h1>
  <h2>"Facial Recognizion Exam"</h2>
</center>
<br>
<br>

<center>
  <p class="text-justify">Estimado alumno para acceder al examen tendrás que verificar tu identidad, asegurase de contar</p>
  <p class="text-justify">Con WebCam, puedes usar tu celular como cámara, si quieres conocer más <a href="https://www.youtube.com/watch?v=OVa-YMdh65I">click aquí</a>.</p>

  <br>
  <p class="text-justify">Para presentar el examen deberás contar con una computadora con cámara web con el objetivo de
    verificar tu <br> identidad, así como una conexión a internet estable.</p>
</center>
<br><br>

<center>
  <div class="container">
    <div class="row">
      <div class="col-sm">

        <div class="card card-1" style="width: 15rem; height: 13rem;"><br>
          <a href="{{ url_for('face_recognition.inicio') }}">
            <center><img class="card-img-top" src="{{ url_for('static',filename='/imagenes/subir3.png') }}" alt=""
                class="img-thumbnail" width="40" height="100"></center>
          </a>
          <div class="card-body">
            <center>
              <p class="parrafo">Subir Imagen</p>
            </center>
          </div>
        </div>
      </div>
      <div class="col-sm">
        <div class="card card-1" style="width: 15rem; height: 13rem;"><br>
          <a href="{{ url_for('face_recognition.indicaciones') }}">
            <center> <br><img class="card-img-top" src="{{ url_for('static',filename='/imagenes/exam.png') }}" alt=""
                class="img-thumbnail" width="100" height="70"></center>
          </a>
          <div class="card-body">
            <center>
              <p class="parrafo">Alumnos</p>
            </center>
          </div>
        </div>
      </div>
    </div>
</center>
<br><br><br>


{% include 'footer.html' %}

app/templates/index2.html
<html>
  <head>
    <title>Video Streaming Demonstration</title>
  </head>
  <body>
    <h1>Video Streaming Demonstration</h1>
    <img id="bg" src="{{ url_for('face_recognition.video_feed') }}">
  </body>
</html>

app/templates/indicaciones.html
{% include 'header.html' %}
<link rel="stylesheet" href="{{ url_for('static',filename='/css/botones.css') }}">
<link rel="stylesheet" href="{{ url_for('static',filename='/css/stylebody.css') }}">
<h2 class="text-center">Indicaciones</h2>
<br><br>
<p class="text-justify">Asegurese de estar en un lugar con buena iluminación para que la cámara capture su rostro de lo contrario no podrá acceder al examen.</p>
<p class="text-justify">El examen solo puede ser tomado por el Aspirante que aparece en el video que fue  entregado con anterioridad.</p>
<br><br>
<div class="container" style="background-color: white">
    <a href="#""><center><img src="{{ url_for('static',filename='/imagenes/reconocimiento.png') }}"  width="290" height="320"></center></a>

</div>


<br><br>
<div class="row align-items-end">
    <div class="col"></div>
    <div class="col"></div>
    <div class="col"><a href="{{ url_for('face_recognition.activar') }}">
        <button onclick="" type="button" class="boton"  style="background-color: #18386B" color="white"> 
        Continuar con el <br> escaneo de rostro </button></a></div>
  </div>




{% include 'footer.html' %}

app/templates/inicio.html
{% include 'header.html' %}

<link rel="stylesheet" href="{{ url_for('static',filename='/css/stylebody.css') }}">
<center>
  <h1>Bienvenid@ a FREE.IA</h1>
  <h2>"Facial Recognizion Exam"</h2>
</center>
<br>
<br>
<center>
    <p class="text-justify">Querid@ Alumno deberá subir una imagen de su rostro con una buena iluminación támbien deberá llenar los datos que sean requeridos como su matricula o nombre.</p>
    <br>
    <p class="text-justify">Una vez finalizado este proceso sus datos serán guardados con éxito y estará listo para presentar su examen en FREE.IA cuando se requiera. </p>

</center>

  
  <br>

<br><br>

<center>
  <div class="container">
    <div class="row">
      <div class="col-sm">

        <div class="card card-1" style="width: 15rem; height: 13rem;"><br>
          <a href="{{ url_for('face_recognition.registrar') }}">
            <center><img class="card-img-top" src="{{ url_for('static',filename='/imagenes/subir3.png') }}" alt=""
                class="img-thumbnail" width="40" height="100"></center>
          </a>
          <div class="card-body">
            <center>
              <p class="parrafo">Subir Imagen</p>
            </center>
          </div>
        </div>

      </div>
      

      </div>
    </div>

</center>
<br><br><br>


{% include 'footer.html' %}

app/templates/login.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reportes UNACH</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ url_for('static',filename='/css/fontawesome-all.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='/css/animate.css') }}">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static',filename='/css/style.css') }}">
</head>
<body >
    <div id="area-login">
        <div id="login">
            <form action="/" method="POST" enctype="multipart/form-data">
                <div class="text-center mb-4">
                    <img src="{{ url_for('static',filename='/imagenes/logo.svg') }}" alt="">
                </div>
                <div class="text-center">
                    <h4>Sistema Reconocimiento facial</h4>
                </div>
                {% for message in get_flashed_messages() %}
                    <div class="alert alert-warning">{{ message }}</div>
                {% endfor %}
                <div class="form-group">
                    <input type="email" name="email" class="form-control" placeholder="Correo UNACH" required>
                </div>
                <div class="form-group">
                    <input name="password" type="password" class="form-control" placeholder="Contraseña" required>
                </div>
                <button type="submit" class="btn btn-main px-4">Entrar</button>
            </form>
        </div>
    </div>
    <div>
        <div class="bg-login"></div>
        <div class="bg-login bg-login-2"></div>
        <div class="bg-login bg-login-3"></div>
    </div>
</body>
</html>
    

app/templates/registrar.html
{% include 'header.html' %}

{% with messages= get_flashed_messages() %}

    {% if messages %}
        <div class="alert alert-danger" role="alert">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>

    {% endif %}

{% endwith %}

<br><br>
<form method="post" action="/aceptar" enctype="multipart/form-data">
    
    <div class="card">
        <div class="card-header">
            Registrar Nuevo Alumno
        </div>
        <div class="card-body">
            <h5 class="card-title">Datos del Alumno</h5>
            <p class="card-text">
                <div  class="form-group">
                    <label for="txtmatricula">Matricula</label>
                    <input id="txtfecha" class="form-control" type="text" name="txtmatricula">
                </div>

                <div class="form-group">
                    <label for="txtnombre">Nombre Completo</label>
                    <input id="txtnombre" class="form-control" value="" type="text" name="txtnombre">
                </div>

                <form>
                    <div class="custom-file">
                      <input type="file" accept="image/png,image/jpeg,image/jpg" class="custom-file-input" id="customFile" name="customFile">
                      <label class="custom-file-label" for="customFile">Choose file</label>
                    </div>
                  </form>
                  
                  <script>
                  // Add the following code if you want the name of the file appear on select
                  $(".custom-file-input").on("change", function() {
                    var fileName = $(this).val().split("\\").pop();
                    $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
                  });
                  </script>

                
                <br><br>
                <div class="form-group">
                    <input onclick="return confirm('¿Todos los datos son Correctos?')" type="submit" class="btn btn-success" value="Aceptar">
                    <a  href="{{ url_for('face_recognition.inicio') }}" class="btn btn-primary">Regresar</a>
                </div>
            </p>
            
        </div>
    </div>
</form>

<br><br>
{% include 'footer.html' %}